# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Pythonic-Functions
version:      0.38
version_from: lib/Acme/Pythonic/Functions.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
license: perl
generated_by: ExtUtils::MakeMaker version 6.17
